### ISSUE TITLE
Question about sorting

### ISSUE THREAD

**Issue by jayhawker6** [mourner/bullshit.js#186]
I just want to know what you use to sort the terms/format the terms. Like what kind of software is used to generate the list etc. I am assuming these were not all sorted by hand and knowing what was used to sort the terms or edit/format the list would be helpful. I'm also just curious.

-Thanks in advance.

**Comment by jayhawker6** [comment]
@mourner ping after 10 business days.

**Comment by mourner** [comment]
It was written by hand.
