### ISSUE TITLE
Package provides too little synergy

### ISSUE THREAD

**Issue by entd** [mourner/bullshit.js#21]
Synergy in this package is not enough. Please expand with more synergy and more inflatable value. With so little synergy it makes brainstorming out-of-box sessions return little redeemable value for special business process.

**Comment by mourner** [comment]
I completely agree with your authoritative and value-added reassessment of this package and will prioritize the matter to be addressed with care and urgency.

**Comment by dzhus** [comment]
posting in quality thread

**Comment by masaeedu** [comment]
I think what is really needed here is some XTreme Programming. I went to five agile conferences this week, and in my post-conference discussions with my Kanban coach I discovered that man months of story points can be realized by small, highly synergized teams when they move fast and break things.
