### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Silent-Hunter** [mourner/bullshit.js#22]
I can't seem to get this to work. I made the bookmark like the readme said, but it doesn't do anything when I click on it.

**Comment by Vanuan** [comment]
Confirm

**Comment by Vanuan** [comment]
Wait, it actually works here:
https://en.wikipedia.org/wiki/Marketing

**Comment by mourner** [comment]
It should work. One problem I see is the https + http mismatch — the browser may refuse to load https bookmarklet code on an http page.

**Comment by mourner** [comment]
OK should work everywhere now.
