### ISSUE TITLE
A chrome extension? how about that?

### ISSUE THREAD

**Issue by fxnoob** [mourner/bullshit.js#69]
I am happy to make one.

**Comment by mikulabc** [comment]
Takes 5 min those simple ones, it takes more time creating the icons

**Comment by fxnoob** [comment]
Here we are 

https://github.com/fxnoob/bullshit-chrome-extension/tree/02a38c0ca83cbc425e1dc404319a513892d20371

**Comment by mourner** [comment]
Awesome 👍
